eureka:
  client:
    register-with-eureka: false

server:
  port: 8100

spring:
  application:
    name: gateway-service
  cloud:
    config:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: http://localhost:8051
          predicates:
          - Path= /api/v1/students/**
        - id: courses
          uri: http://localhost:8052
          predicates:
          - Path= /api/v1/courses/**
